# Generated by Django 2.2.1 on 2019-12-21 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Last login'),
        ),
    ]
