# Generated by Django 2.2.1 on 2019-12-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
        ('users', '0002_auto_20191221_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interests',
            field=models.ManyToManyField(blank=True, to='me.Interest'),
        ),
    ]
