# Generated by Django 2.2.1 on 2019-12-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='interests',
        ),
    ]
