# Generated by Django 2.2.1 on 2020-01-19 00:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_account_active_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default-pfp.png', upload_to='pfps'),
        ),
    ]
