# Generated by Django 2.2.1 on 2020-01-23 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='falahprograms.City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last login'),
        ),
    ]
