# Generated by Django 2.2.1 on 2020-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('INVALID', 'INVALID'), ('AUTHENTICATED', 'AUTHENTICATED')], max_length=40)),
                ('applicationId', models.CharField(max_length=30)),
                ('userId', models.CharField(max_length=100)),
                ('sand', models.CharField(max_length=30)),
                ('deviceId', models.CharField(max_length=100)),
            ],
        ),
    ]
