# Generated by Django 2.2.1 on 2019-12-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City value')),
                ('verbose_name', models.CharField(max_length=70, verbose_name='City name')),
                ('country', models.CharField(choices=[('usa', 'USA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='images')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('recurringClass', 'Recurring class'), ('oneTime', 'One time event')], max_length=50)),
                ('primary_subject', models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('foreign_language', 'Foreign Language'), ('science', 'Science'), ('social_science', 'Social Science'), ('political', 'Political'), ('skills', 'Skills'), ('other', 'Other')], max_length=50)),
                ('secondary_subject', models.CharField(choices=[('elementry', 'Elementry school'), ('preAlgebra', 'Pre-algebra'), ('algebra', 'Algebra'), ('geometry', 'Geometry'), ('basicApp', 'Basic Applications'), ('preCalculus', 'Pre-calculus'), ('calculus', 'Calculus'), ('mcalc', 'Multivariable calculus'), ('lalgebra', 'Linear algebra'), ('advancedApp', 'Advanced applications'), ('astro', 'Astrophysics'), ('bio', 'Biology'), ('chem', 'Chemistry'), ('cs', 'Computer science'), ('orgo', 'Organic chemistry'), ('physics', 'Physics'), ('medicine', 'Medicine'), ('zoology', 'Zoology'), ('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('poetry', 'Poetry'), ('spanish', 'Spanish'), ('german', 'German'), ('french', 'French'), ('russian', 'Russian'), ('arabic', 'Arabic'), ('chinese', 'Chinese'), ('econ', 'Economics'), ('history', 'History'), ('polsci', 'Political science'), ('sociology', 'Sociology'), ('psych', 'Psychology'), ('voting', 'Voting'), ('immigration', 'Immigration law'), ('taxes', 'Taxes'), ('sports', 'Sports'), ('woodworking', 'Woodworking'), ('fishing', 'Fishing/Hunting'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.City')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('stop', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Venue', verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Coordinates', verbose_name='Coordinates'),
        ),
    ]
