# Generated by Django 2.2.1 on 2019-12-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falahprograms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='verbose_name',
            field=models.CharField(max_length=70, verbose_name='City verbose name'),
        ),
    ]
