# Generated by Django 2.2.1 on 2019-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falahprograms', '0003_auto_20191223_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_attendees',
            field=models.IntegerField(blank=True, default=30),
            preserve_default=False,
        ),
    ]
