# Generated by Django 2.2.1 on 2020-01-23 03:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('falahprograms', '0004_program_max_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default='city.jpg', upload_to='cities'),
        ),
        migrations.AddField(
            model_name='venue',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default='venue.jpg', upload_to='venues'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(default='program.jpg', upload_to='programs'),
        ),
    ]
