# Generated by Django 2.2.1 on 2020-01-26 23:33

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('falahprograms', '0005_auto_20200123_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=50)),
                ('img', imagekit.models.fields.ProcessedImageField(default='city.jpg', upload_to='cities')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Coordinates', verbose_name='Coordinates')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falahprograms.Country', verbose_name='country'),
        ),
    ]
