# Generated by Django 2.2.1 on 2019-12-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('foreign_language', 'Foreign Language'), ('science', 'Science'), ('social_science', 'Social Science'), ('political', 'Political'), ('skills', 'Skills'), ('other', 'Other')], max_length=50)),
                ('intensity', models.FloatField()),
            ],
        ),
    ]
